backupDestination: /var/backups
databases: # Eğer boş bırakılırsa tüm veritabanları yedeklenir (if databases is empty, all databases will be backed up)
  - db1
  - db2
removeLocal: true
archivePass: "encryptionPassword"
s3:
  enabled: true
  region: aws region
  bucket: s3 bucket
  path: backup path
  accessKey: s3 access key
  secretKey: s3 secret key
minio:
  enabled: true
  endpoint: minio endpoint
  bucket: minio bucket
  path: backup path
  accessKey: minio access key
  secretKey: minio secret key
  secure: false
  insecureSkipVerify: false
notify:
  email:
    enabled: true
    onlyOnError: false
    info:
      smtpHost: smtp.gmail.com
      smtpPort: 587
      username: sender@example.com
      from: sender@example.com
      password: 123456
      to: recipient@example.com
    error:
      smtpHost: smtp.gmail.com
      smtpPort: 587
      username: sender@example.com
      from: sender@example.com
      password: 123456
      to: recipient@example.com
  mattermost:
    enabled: false
    info:
      url: mattermost url
      channelId: channel id
      apiToken: api token
    error:
      url: mattermost url
      channelId: channel id
      apiToken: api token

log:
  enabled: true
  file: /var/log/pgsql-backup.log
